ar10_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("record.urls")),
]

record/urls.py
from django.urls import path

from . import views

app_name = "record"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("training/", views.training_data_list, name="training_data_list"),
    path("training/new/", views.training_data_new, name="training_data_new"),
    path(
        "training/<int:pk>/edit/", views.training_data_edit, name="training_data_edit"
    ),
    path(
        "training/<int:pk>/delete/",
        views.training_data_delete,
        name="training_data_delete",
    ),
    path("competition/", views.competition_data_list, name="competition_data_list"),
    path("competition/new", views.competition_data_new, name="competition_data_new"),
    path(
        "competition/<int:pk>/edit/",
        views.competition_data_edit,
        name="competition_data_edit",
    ),
    path(
        "competition/<int:pk>/delete",
        views.competition_data_delete,
        name="competition_data_delete",
    ),
]

templates/competition/competition.html
<!-- templates/competition/competition.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Competition Data{% endblock title %}

{% block content %}
<div class="container">
<h6 class="mt-4 display-6">Add Competition Record</h6>
<form action="{% url 'record:competition_data_new' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row mt-3">
        {{ form.competition_name.errors }}
        <label for="{{ form.competition_name.id_for_label }}" class="col-sm-2 col-form-label">Competition Name:</label>
        <div class="col-sm-8">
        {{ form.competition_name|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3">
        {{ form.date.errors }}
        <label for="{{ form.date.id_for_label }}" class="col-sm-2 col-form-label">Competition Date:</label>
        <div class="col-sm-8">
        {{ form.date|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3">
        {{ form.match_number.errors }}
        <label for="{{ form.match_number.id_for_label }}" class="col-sm-2 col-form-label">Match Number:</label>

        <div class="col-sm-8">
        {{ form.match_number|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.qual_score.errors }}
        <label for="{{ form.qual_score.id_for_label }}" class="col-sm-2 col-form-label">Qualification Score:</label>

        <div class="col-sm-8">
        {{ form.qual_score|add_class:"form-control" }}
        </div>
    </div>
    <input class="btn btn-primary" type="submit" value="Save">
    <a type="button" class="btn btn-outline-secondary" href="{% url 'record:competition_data_list' %}">Cancel</a>
</form>
</div>
{% endblock content %}

templates/competition/competition_data_delete.html
<!-- templates/competition/competition_data_delete.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h6 class="mt-4 mb-3 display-6">Are you sure you want to delete this item?</h6>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a type="button" class="btn btn-outline-secondary" href="{% url 'record:competition_data_list' %}">Go back</a>
</form>
</div>
{% endblock %}

templates/competition/competition_data_edit.html
<!-- templates/competition/competition_data_edit.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Edit Competition Data{% endblock title %}

{% block content %}
<div class="container">
    <h6 class="mt-4 display-6">Edit Competition Data</h2>
<form  method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row mt-3">
        {{ form.subject.errors }}
        <label for="{{ form.competition_name.id_for_label }}" class="col-sm-2 col-form-label">Competition Name:</label>
        <div class="col-sm-8">
        {{ form.competition_name|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3">
        {{ form.subject.errors }}
        <label for="{{ form.date.id_for_label }}" class="col-sm-2 col-form-label">Competition Date:</label>
        <div class="col-sm-8">
        {{ form.date|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3">
        {{ form.subject.errors }}
        <label for="{{ form.match_number.id_for_label }}" class="col-sm-2 col-form-label">Match Number:</label>

        <div class="col-sm-8">
        {{ form.match_number|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.qual_score.id_for_label }}" class="col-sm-2 col-form-label">Qualification Score:</label>

        <div class="col-sm-8">
        {{ form.qual_score|add_class:"form-control" }}
        </div>
    </div>
    <input class="btn btn-primary" type="submit" value="Save">
    <a type="button" class="btn btn-outline-secondary" href="{% url 'record:competition_data_list' %}">Cancel</a>
</form>
{% endblock %}

templates/competition/competition_data_list.html
<!-- templates/competition/competition_data_list.html -->
{% extends 'base.html' %}

{% block title %}Competition Data{% endblock title %}

{% block content %}
<div class="container">
    <h6 class="mt-4 display-6">Competition Results</h6>
    <table class="table mt-3">
        <thead>
            <tr>
                <th scope="col">Competition</th>
                <th scope="col">Date</th>
                <th scope="col">Match Number</th>
                <th scope="col">Qualification Score</th>
            </tr>
        </thead>

        <tbody>
            {% for data in competition_data_page_obj %}
            <tr>
                <td>{{ data.competition_name }}</td>
                <td>{{ data.date }}</td>
                <td>{{ data.match_number }}</td>
                <td>{{ data.qual_score }}</td>
                {% if data.user == request.user %}
                <td><a type="button" class="btn btn-outline-secondary btn-sm" href="{% url 'record:competition_data_edit' pk=data.pk %}" role="button">Edit</a>
                <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'record:competition_data_delete' pk=data.pk %}" role="button">Delete</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if competition_data_page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ competition_data_page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ competition_data_page_obj.number }} of {{ competition_data_page_obj.paginator.num_pages }}.
            </span>
    
            {% if competition_data_page_obj.has_next %}
                <a href="?page={{ competition_data_page_obj.next_page_number }}">next</a>
                <a href="?page={{ competition_data_page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}