ar10_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("record.urls")),
]

record/urls.py
from django.urls import path

from . import views

app_name = "record"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("training/", views.training_data_list, name="training_data_list"),
    path("training/new/", views.training_data_new, name="training_data_new"),
    path(
        "training/<int:pk>/edit/", views.training_data_edit, name="training_data_edit"
    ),
    path(
        "training/<int:pk>/delete/",
        views.training_data_delete,
        name="training_data_delete",
    ),
    path("competition/", views.competition_data_list, name="competition_data_list"),
    path("competition/new", views.competition_data_new, name="competition_data_new"),
    path(
        "competition/<int:pk>/edit/",
        views.competition_data_edit,
        name="competition_data_edit",
    ),
    path(
        "competition/<int:pk>/delete",
        views.competition_data_delete,
        name="competition_data_delete",
    ),
]

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>10m Air Rifle Performance Tracker</title>

    <!-- Bootstrap css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- Custon css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <span class="navbar-brand mb-0 h1 fs-4">AR10</span>
          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
              <a href="{% url 'record:dashboard' %}" class="nav-item nav-link active">
                <i class="bi-bar-chart me-1"></i>Dashboard
              </a>
              <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                  <i class="bi-trophy me-1"></i>Competition
                </a>
                <div class="dropdown-menu">
                  <a href="{% url 'record:competition_data_new' %}" class="dropdown-item">Add Competition Data</a>
                  <a href="{% url 'record:competition_data_list' %}" class="dropdown-item">View Competition Data</a>
                  </div>
              </div>
              <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                  <i class="bi-bullseye me-1"></i>Training
                </a>
                <div class="dropdown-menu">
                  <a href="{% url 'record:training_data_new' %}" class="dropdown-item">Add Training Data</a>
                  <a href="{% url 'record:training_data_list' %}" class="dropdown-item">View Training Data</a>
                </div>
              </div>
            </div>
            <div class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-item nav-link">Log Out</a>
              {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link">Log In</a>
              {% endif %}
            </div>
          </div>
      </div>
    </nav>

    <main>
      <div class="container">
        {% if messages %}
        <div class="row text-center">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
      {% block content %}
      {% endblock content %}
    </main>
    <footer class="py-3 my-4">
      <div class="container">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'record:dashboard' %}" class="nav-link px-2 text-muted">Dashboard</a></li>
        <li class="nav-item"><a href="{% url 'record:competition_data_list' %}" class="nav-link px-2 text-muted">Competition Data</a></li>
        <li class="nav-item"><a href="{% url 'record:training_data_list' %}" class="nav-link px-2 text-muted">Training Data</a></li>
      </ul>
      <p class="text-center text-muted">Made by Michael Knott</p>
    </div>
    </footer>

  <!-- Bootstrap Javascript and Popper -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  </body>
</html>

templates/dashboard.html
<!-- templates/dashboard.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="custom-overview">
  <div class="container mt-2 h-100 d-flex">

    <div class="row h-25 align-items-center">
      <div class="col">
        {% if user.is_authenticated %}
        <p class="lead">Hello, {{ user.get_username }}</p>
        {% else %}
        <p class="lead">Hello, User. Please Log In</p>
        {% endif %}
      </div>
    </div>
</section>

<section class="custom-score-overview">
  <div class="container mt-2">
    <div class="row">
      <div class="col">
        <h1 class="h4 text-muted mb-3">Training Scores</h1>
      </div>
      <div class="col">
        <h1 class="h4 text-muted md-3">Competition Scores</h1>
      </div>
    </div>
    <div class="row">
      <div class="col d-flex justify-content-start">
        <div class="card me-3" style="width: 9rem;">
          <div class="card-body">
            <h5 class="card-title">PB</h5>
            <p class="card-text">{{ training_pb.score__max }}</p>
          </div>
        </div>

        <div class="card ms-3" style="width: 9rem;">
          <div class="card-body">
            <h5 class="card-title">Avg. Top 3</h5>
            <p class="card-text">{{ training_top3_avg.score__avg|floatformat:2 }}</p>
          </div>
        </div>
      </div>

      <div class="col d-flex justify-content-start">
        <div class="card me-3" style="width: 9rem;">
          <div class="card-body">
            <h5 class="card-title">PB</h5>
            <p class="card-text">{{ comp_pb.qual_score__max }}</p>
          </div>
        </div>

        <div class="card ms-3" style="width: 9rem;">
          <div class="card-body">
            <h5 class="card-title">Avg. Top 3</h5>
            <p class="card-text">{{ comp_top3_avg.qual_score__avg|floatformat:2 }}</p>
          </div>
        </div>
      </div>
  </div>
</section>

<section class="score-charts">
  <div class="container mt-4">
    <div class="row">
      <div class="col">
          <canvas id="trainingScores"></canvas>
      </div>
      <div class="col">
          <canvas id="compScores"></canvas>
      </div>

      <script>
        const data = {
            labels: [{% for item in training_data %}"{{ item.date }}"{% if not forloop.last %},{% endif %}{% endfor %}],
                datasets: [{
                    label: "Scores",
                    data: [{% for item in training_data %}{{ item.score}}{% if not forloop.last %},{% endif %}{% endfor %}],
                    backgroundColor: ['rgba(7, 7, 7, 1)'],
                    borderColor: ['rgba(7, 7, 7, 1)'],
                    borderWidth: 3
                },
              ]
        };

        const config = {
            type: 'line',
            data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                      position: 'bottom',
                      display: false,
                    },
                    title: {
                      display: false,
                      text: 'Training Scores'
                    }
                },
                scales: {
                    y: {
                      suggestedMin: 600,
                      suggestedMax: 650,
                    }
                }
            }
        };

        const trainingScores = new Chart(document.getElementById('trainingScores'), config);


    const data2 = {
        labels: [{% for data in competition_data %}"{{ data.date }}"{% if not forloop.last %},{% endif %}{% endfor %}],
            datasets: [{
                label: "Scores",
                data: [{% for data in competition_data %}{{ data.qual_score }}{% if not forloop.last %},{% endif %}{% endfor %}],
                backgroundColor: ['rgba(7, 7, 7, 1)'],
                borderColor: ['rgba(7, 7, 7, 1)'],
                borderWidth: 3
            },
          ]
    };

    const config2 = {
        type: 'line',
        data: data2,
        options: {
            responsive: true,
            plugins: {
                legend: {
                  position: 'bottom',
                  display: false,
                },
                title: {
                  display: false,
                  text: 'Competition Scores'
                }
            },
            scales: {
              y: {
                suggestedMin: 600,
                suggestedMax: 650,
              }
          }
        }
    };

    const compScores = new Chart(document.getElementById('compScores'), config2);
  </script>
  </div>
  </div>
  </section>

</section>

<section class="custom-scatt-overview">
  <div class="container mt-4">
    <div class="row">
      <div class="col d-flex justify-content-start">
        <h1 class="h4 text-muted mb-3">SCATT</h1>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">10.0</h5>
              <p class="card-text">{{ training_data_avgs.ten_zero__avg|floatformat:2 }} %</p>
            </div>
          </div>

          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">10a.0</h5>
              <p class="card-text">{{ training_data_avgs.ten_azero__avg|floatformat:2 }} %</p>
            </div>
          </div>

          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">10.5</h5>
              <p class="card-text">{{ training_data_avgs.ten_five__avg|floatformat:2 }} %</p>
            </div>
          </div>

          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">10a.5</h5>
              <p class="card-text">{{ training_data_avgs.ten_azero__avg|floatformat:2 }} %</p>
            </div>
          </div>
        </div>

        <div class="col d-flex justify-content-center">
          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">T</h5>
              <p class="card-text">{{ training_data_avgs.aiming_time__avg|floatformat:2 }}</p>
            </div>
          </div>

          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">S1</h5>
              <p class="card-text">{{ training_data_avgs.s1__avg|floatformat:2 }}</p>
            </div>
          </div>

          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">S2</h5>
              <p class="card-text">{{ training_data_avgs.s2__avg|floatformat:2 }}</p>
            </div>
          </div>

          <div class="card mx-2" style="width: 7rem;">
            <div class="card-body">
              <h5 class="card-title">DA</h5>
              <p class="card-text">{{ training_data_avgs.da__avg|floatformat:2 }}</p>
            </div>
          </div>
        </div>

      </div>
    </div>
 </div>
</section>

<section class="training-charts">
<div class="container mt-4">
  <div class="row">
    <div class="col">
        <canvas id="scatt1"></canvas>
    </div>
    <div class="col">
        <canvas id="scatt2"></canvas>
    </div>

    <script>
      const data3 = {
          labels: [{% for item in training_data %}"{{ item.date }}"{% if not forloop.last %},{% endif %}{% endfor %}],
              datasets: [{
                  label: "10a0",
                  data: [{% for item in training_data %}{{ item.ten_azero }}{% if not forloop.last %},{% endif %}{% endfor %}],
                  backgroundColor: ['rgba(7, 7, 7, 1)'],
                  borderColor: ['rgba(7, 7, 7, 1)'],
                  borderWidth: 3
              },
              {
                  label: "10a5",
                  data: [{% for item in training_data %}{{ item.ten_afive }}{% if not forloop.last %},{% endif %}{% endfor %}],
                  backgroundColor: ['rgba(7, 7, 7, 0.33)'],
                  borderColor: ['rgba(7, 7, 7, 0.33)'],
                  borderDash: [5, 5],
                  borderWidth: 3
              }]
      };

      const config3 = {
          type: 'line',
          data: data3,
          options: {
              responsive: true,
              plugins: {
                  legend: {
                    position: 'bottom',
                  },
                  title: {
                    display: true,
                    text: 'Stability of Hold'
                  }
              },
              scales: {
                y: {
                  suggestedMin: 70,
                  suggestedMax: 100,
                }
            }
          }
      };

      const scatt1 = new Chart(document.getElementById('scatt1'), config3);


  const data4 = {
      labels: [{% for item in training_data %}"{{ item.date }}"{% if not forloop.last %},{% endif %}{% endfor %}],
          datasets: [{
              label: "10.0",
              data: [{% for item in training_data %}{{ item.ten_zero }}{% if not forloop.last %},{% endif %}{% endfor %}],
              backgroundColor: ['rgba(7, 7, 7, 1)'],
              borderColor: ['rgba(7, 7, 7, 1)'],
              borderWidth: 3
          },
          {
              label: "10.5",
              data: [{% for item in training_data %}{{ item.ten_five }}{% if not forloop.last %},{% endif %}{% endfor %}],
              backgroundColor: ['rgba(7, 7, 7, 0.33)'],
              borderColor: ['rgba(7, 7, 7, 0.33)'],
              borderDash: [5, 5],
              borderWidth: 3
          }]
  };

  const config4 = {
      type: 'line',
      data: data4,
      options: {
          responsive: true,
          plugins: {
              legend: {
                position: 'bottom',
              },
              title: {
                display: true,
                text: 'Aiming Accuracy'
              }
          },
          scales: {
            y: {
              suggestedMin: 70,
              suggestedMax: 100,
            }
        }
      }
  };

  const scatt2 = new Chart(document.getElementById('scatt2'), config4);
</script>
</div>
</div>
</section>
{% endblock %}