ar10_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("record.urls")),
]

record/urls.py
from django.urls import path

from . import views

app_name = "record"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("training/", views.training_data_list, name="training_data_list"),
    path("training/new/", views.training_data_new, name="training_data_new"),
    path(
        "training/<int:pk>/edit/", views.training_data_edit, name="training_data_edit"
    ),
    path(
        "training/<int:pk>/delete/",
        views.training_data_delete,
        name="training_data_delete",
    ),
    path("competition/", views.competition_data_list, name="competition_data_list"),
    path("competition/new", views.competition_data_new, name="competition_data_new"),
    path(
        "competition/<int:pk>/edit/",
        views.competition_data_edit,
        name="competition_data_edit",
    ),
    path(
        "competition/<int:pk>/delete",
        views.competition_data_delete,
        name="competition_data_delete",
    ),
]

templates/training/training.html
<!-- templates/training/training.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Training Data{% endblock title %}

{% block content %}
<div class="container">
<h6 class="mt-4 display-6">Add Training Record</h6>
<form action="{% url 'record:training_data_new' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row mt-3">
        {{ form.date.errors|add_class:"form-control" }}
        <label for="{{ form.date.id_for_label }}" class="col-sm-2 col-form-label">Training Date:</label>
        <div class="col-sm-8">
        {{ form.date|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3">
        {{ form.number_shots.errors }}
        <label for="{{ form.number_shots.id_for_label }}" class="col-sm-2 col-form-label">Number of Shots:</label>

        <div class="col-sm-8">
        {{ form.number_shots|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.score.errors }}
        <label for="{{ form.score.id_for_label }}" class="col-sm-2 col-form-label">Live Score:</label>

        <div class="col-sm-8">
        {{ form.score|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.target_distance.errors }}
        <label for="{{ form.target_distance.id_for_label }}" class="col-sm-2 col-form-label">Target Distance:</label>

        <div class="col-sm-8">
        {{ form.target_distance|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.f_coefficient.errors }}
        <label for="{{ form.f_coefficient.id_for_label }}" class="col-sm-2 col-form-label">F co-efficient</label>

        <div class="col-sm-8">
        {{ form.f_coefficient|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.aiming_time.errors }}
        <label for="{{ form.aiming_time.id_for_label }}" class="col-sm-2 col-form-label">T</label>

        <div class="col-sm-8">
        {{ form.aiming_time|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.ten_zero.errors }}
        <label for="{{ form.ten_zero.id_for_label }}" class="col-sm-2 col-form-label">10.0</label>

        <div class="col-sm-8">
        {{ form.ten_zero|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.ten_azero.errors }}
        <label for="{{ form.ten_azero.id_for_label }}" class="col-sm-2 col-form-label">10a.0</label>

        <div class="col-sm-8">
        {{ form.ten_azero|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.ten_five.errors }}
        <label for="{{ form.ten_five.id_for_label }}" class="col-sm-2 col-form-label">10.5</label>

        <div class="col-sm-8">
        {{ form.ten_five|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.ten_afive.errors }}
        <label for="{{ form.ten_afive.id_for_label }}" class="col-sm-2 col-form-label">10a.5</label>

        <div class="col-sm-8">
        {{ form.ten_afive|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.s1.errors }}
        <label for="{{ form.s1.id_for_label }}" class="col-sm-2 col-form-label">S1</label>

        <div class="col-sm-8">
        {{ form.s1|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.s2.errors }}
        <label for="{{ form.s2.id_for_label }}" class="col-sm-2 col-form-label">S2</label>

        <div class="col-sm-8">
        {{ form.s2|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.da.errors }}
        <label for="{{ form.da.id_for_label }}" class="col-sm-2 col-form-label">DA</label>

        <div class="col-sm-8">
        {{ form.da|add_class:"form-control" }}
        </div>
    </div>
    <input class="btn btn-primary" type="submit" value="Save">
    <a type="button" class="btn btn-outline-secondary" href="{% url 'record:training_data_list' %}">Cancel</a>
</form>
</div>
{% endblock content %}

templates/training/training_data_delete.html
<!-- templates/training/training_data_delete.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h6 class="mt-4 mb-3 display-6">Are you sure you want to delete this item?</h6>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a type="button" class="btn btn-outline-secondary" href="{% url 'record:training_data_list' %}">Go back</a>
</form>
</div>
{% endblock %}

templates/training/training_data_edit.html
<!-- templates/training/training_data_edit.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Training Data{% endblock title %}

{% block content %}
<div class="container">
<h6 class="mt-4 display-6">Edit Training Record</h6>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row mt-3">
        {{ form.subject.errors }}
        <label for="{{ form.date.id_for_label }}" class="col-sm-2 col-form-label">Training Date:</label>
        <div class="col-sm-8">
        {{ form.date|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3">
        {{ form.subject.errors }}
        <label for="{{ form.number_shots.id_for_label }}" class="col-sm-2 col-form-label">Number of Shots:</label>

        <div class="col-sm-8">
        {{ form.number_shots|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.score.id_for_label }}" class="col-sm-2 col-form-label">Live Score:</label>

        <div class="col-sm-8">
        {{ form.score|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.target_distance.id_for_label }}" class="col-sm-2 col-form-label">Target Distance:</label>

        <div class="col-sm-8">
        {{ form.target_distance|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.f_coefficient.id_for_label }}" class="col-sm-2 col-form-label">F co-efficient</label>

        <div class="col-sm-8">
        {{ form.f_coefficient|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.aiming_time.id_for_label }}" class="col-sm-2 col-form-label">T</label>

        <div class="col-sm-8">
        {{ form.aiming_time|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.ten_zero.id_for_label }}" class="col-sm-2 col-form-label">10.0</label>

        <div class="col-sm-8">
        {{ form.ten_zero|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.ten_azero.id_for_label }}" class="col-sm-2 col-form-label">10a.0</label>

        <div class="col-sm-8">
        {{ form.ten_azero|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.ten_five.id_for_label }}" class="col-sm-2 col-form-label">10.5</label>

        <div class="col-sm-8">
        {{ form.ten_five|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.ten_afive.id_for_label }}" class="col-sm-2 col-form-label">10a.5</label>

        <div class="col-sm-8">
        {{ form.ten_afive|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.s1.id_for_label }}" class="col-sm-2 col-form-label">S1</label>

        <div class="col-sm-8">
        {{ form.s1|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.s2.id_for_label }}" class="col-sm-2 col-form-label">S2</label>

        <div class="col-sm-8">
        {{ form.s2|add_class:"form-control" }}
        </div>
    </div>
    <div class="row mt-3 mb-4">
        {{ form.subject.errors }}
        <label for="{{ form.da.id_for_label }}" class="col-sm-2 col-form-label">DA</label>

        <div class="col-sm-8">
        {{ form.da|add_class:"form-control" }}
        </div>
    </div>
    <input class="btn btn-primary" type="submit" value="Save">
    <a type="button" class="btn btn-outline-secondary" href="{% url 'record:training_data_list' %}">Cancel</a>
</form>
</div>
{% endblock content %}

templates/training/training_data_list.html
<!-- templates/training/training_data_list.html -->
{% extends 'base.html' %}

{% block title %}Training Data{% endblock title %}

{% block content %}
<div class="container">
    <h6 class="mt-4 display-6">Training Results</h6>
    <table class="table mt-3">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col"># of Shots</th>
                <th scope="col">Live Score</th>
                <th scope="col">Distance</th>
                <th scope="col">F co-eff.</th>
                <th scope="col">T</th>
                <th scope="col">10.0</th>
                <th scope="col">10a.0</th>
                <th scope="col">10.5</th>
                <th scope="col">10a.5</th>
                <th scope="col">S1</th>
                <th scope="col">S2</th>
                <th scope="col">DA</th>
            </tr>
        </thead>

        <tbody>
            {% for data in training_data_page_obj %}
            <tr>
                <td>{{ data.date }}</td>
                <td>{{ data.number_shots }}</td>
                <td>{{ data.score }}</td>
                <td>{{ data.target_distance }}</td>
                <td>{{ data.f_coefficient }}</td>
                <td>{{ data.aiming_time }}</td>
                <td>{{ data.ten_zero }}</td>
                <td>{{ data.ten_azero }}</td>
                <td>{{ data.ten_five }}</td>
                <td>{{ data.ten_afive }}</td>
                <td>{{ data.s1 }}</td>
                <td>{{ data.s2 }}</td>
                <td>{{ data.da }}</td>
                {% if data.user == request.user %}
                <td><a type="button" class="btn btn-outline-secondary btn-sm" href="{% url 'record:training_data_edit' pk=data.pk %}" role="button">Edit</a>
                <a type="button" class="btn btn-outline-danger btn-sm" href="{% url 'record:training_data_delete' pk=data.pk %}" role="button">Delete</a></td>
                {% endif %}
            </tr>
            {% endfor %}
                </span>
            </div>
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if training_data_page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ training_data_page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ training_data_page_obj.number }} of {{ training_data_page_obj.paginator.num_pages }}.
            </span>
    
            {% if training_data_page_obj.has_next %}
                <a href="?page={{ training_data_page_obj.next_page_number }}">next</a>
                <a href="?page={{ training_data_page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
</div>
{% endblock content %}